### ISSUE TITLE
Spotify crashes when redirecting to artists' page from search

### ISSUE THREAD

**Issue by Yellow-Pelicon** [aleksilassila/SpotifyMorePopularSongs#1]
Hey, I love the concept of this tweak so much, but sometimes I seem to be unable to search for an artist and go to their page. Spotify just crashes after that. If I go through "Your Library" and then go to the "Artists" page it seems to work fine. Uninstalling the tweak resolves the issue.

I have included some info if it proves to be helpful

Device info:
XS Max, 13.5 Unc0ver
Spotify Ver: 8.5.68.921
Spotify Tweaks: Colorflow 5, Lyrication, Spotify Listening History, SpotifyMorePopularSongs, SpotifyPlaylistNumberOfSongs

**Comment by aleksilassila** [comment]
Hey,
I've had multiple reports of this and it has since been fixed in version 0.0.2. Make sure to update your tweak!
